### PR TITLE
pass position in info panel

### LINKED ISSUE #16: info_panel is not working
In `shiny_panel` position argument is not passed properly to `display` function.
Error message:
`Error in strsplit(position, " ") : non-character argument`

### PR DESCRIPTION
**Pull request by jakubnowicki**
Closes #16 

Changed way of passing position argument in `info_panel` to avoid checking arguments of the parent function.

### CODE REVIEW

File: R/busy.R [hunk 1]
```diff
@@ -103,7 +103,7 @@ busy <- function(loader = "dots", position = "top right") {
     tags$script(
       'function checkifrunning() {
         var is_running = $("html").attr("class").includes("shiny-busy");
-        if (is_running){
+        if (is_running){ #nolint
```
Comment (dokato) [inline R/busy.R]: actually here we can fix it. Missed space between brackets
