### PR TITLE
8 placing more than one box same corner

### LINKED ISSUE #8: Placing more than box
Placing more than one infobox is not working properly.

One thing that they cover themselves if placed in the same spot. Probably should be joined in one div that is placed.

Also when placing in different corners behavior is broken. I checked it out and it's due to the adding multiple divs with `id = "shinyinfo"`. This causes the second box to use positions placement information of itself as well as those of previously created boxes. In some cases causing the box to cover some or all of the app screen (with _bottom left_).

Switching to classes or adding more specific ids for divs of different functions (for _busy, git_info, powerd_by_, etc.) should solve it.  As for the first problem, maybe the div in a corner should be inserted first and then inserting additional elements into it would solve that.

### PR DESCRIPTION
**Pull request by mdubel**
This PR fully resolved #8 
User is supposed to put all the info boxes in the single `infoPanel` (camel case used to be in line with Shiny mainPanel, sidebarPanel and so on; to be discussed) where position can be specified just once and boxes do not overlap themselves. If other positions are used inside they're overwritten by `infoPanel` position.

User still can put info boxes in different corners, can specify them outside the `infoPanel` (or not even use it at all if there is a single box in each corner). See app example for the usage.

I'll think through the idea you've mentioned in comment for the other PR.

### CODE REVIEW

**Comment by dokato** [comment]
@mdubel could you try to rebase to master to fix the CI?

File: examples/app.R [hunk 1]
```diff
@@ -5,7 +5,12 @@ VERSION = "1.2.2"
 
 shinyApp(
   ui = tagList(
-    shiny.info::git_info(position = "bottom left"),
+    shiny.info::infoPanel(
```
Comment (dokato) [inline examples/app.R]: The variable styling is quite a delicate thing in shiny world. We prefer snake_case usually, but for consistency you could introduce `infoPanel` as a wrapper to `info_panel`

**Comment by mdubel** [comment]
> @mdubel could you try to rebase to master to fix the CI?

@dokato It is rebased and I can't quite find what CI does not like in my code. I'll examine it further.

File: R/panel.R [hunk 2]
```diff
@@ -0,0 +1,10 @@
+#' Creates a panel for all info boxes so they do not overlap
+#'
+#' @param position character with position of the parameter. Default "top right".
+#' @param ... calls with info elements
+#'
+#' @return div which wraps your all info boxes to display it in the {position} corner of your shiny app.
+#' @export
+infoPanel <- function(position = "top left", ...) {
```
Comment (dokato) [inline R/panel.R]: Let's make it default top right and change the order: `function(..., position = "top right")`

File: R/display.R [hunk 3]
```diff
@@ -2,25 +2,35 @@
...
   tagList( #nolint
     tags$head(
       tags$style(
         HTML(
           glue::glue(
             "
-            #shinyinfo {{
-              position: fixed;
+            #{type_id} {{
+              position: {fixed_layout};
```
Comment (dokato) [inline R/display.R]: What about creating a common class for all style-related features and leave position related to these items? I think it's more elegant, but I'm happy to discuss.

**Comment by dokato** [comment]
> > @mdubel could you try to rebase to master to fix the CI?
> 
> @dokato It is rebased and I can't quite find what CI does not like in my code. I'll examine it further.

I think it's something related to pdf generation from manual. Check your NAMESPACE and make sure you called `devtools::document()`

File: R/display.R [hunk 4]
```diff
@@ -2,49 +2,61 @@
...
 #' @import glue
-display <- function(message, position = "top right") {
+display <- function(message, position = "top right", type = "message") {
   allowed_positions <- c("top right", "top left", "bottom right", "bottom left")
   if (!position %in% allowed_positions)
     stop("Position argument not allowed.")
+  fixed_layout <- "fixed"
+  # when called from inside infoPanel function position arguments are supposed to be overwritten
+  # and css position should be empty
+  plausible_info_panel_call <- sys.call(max(-8, -length(sys.calls()) + 1))
```
Comment (mdubel) [inline R/display.R]: @dokato I've found that that `sys.call` was causing problems when doing `devtools::check`. I don't know why it worked when running example app manually then. I was aware that this is a "risky" point in the code, but had no other idea how, in the most user friendly way*, recognize if sth is called from inside `info_panel` or not. If you have some please share.

*i.e users use info boxes the same way no matter if they are used inside info_panel or not and do not need to specify position each time.

Comment (dokato) [reply R/display.R]: I see... but it looks like this condition is wrong: `max(-8, -length(sys.calls()) + 1)`. When I run it with just `sys.call()` all works just fine.

File: R/panel.R [hunk 5]
```diff
@@ -0,0 +1,21 @@
+#' Creates a panel for all info boxes so they do not overlap
+#'
+#' @param ... calls with info elements
+#' @param position character with position of the parameter. Default "top right".
+#'
+#' @return div which wraps your all info boxes to display it in the position corner of your shiny app.
+#' @export
+info_panel <- function(..., position = "top right") {
+  display(tagList(...), position = position, type = "info_panel") #nolint
```
Comment (dokato) [inline R/panel.R]: tagList should be imported here

Comment (dokato) [reply R/panel.R]: and then probably you can lint

Comment (mdubel) [reply R/panel.R]: > I run it with just sys.call() all works just fine.
Yeap, there used to be just `sys.call(-8)` and was working perfectly when I've run example app, but failed for `devtools::check()`. And that was the reason why CI through error as -8 was outside the call stack. 
If you had in mind something that solves the CI issue please explain.

Comment (dokato) [reply R/panel.R]: Why is `-8` even needed? I suggested using `sys.call()` on its own. It passed my checks locally.

BTW I have no idea why this comment landed here.

Comment (mdubel) [reply R/panel.R]: Maybe using simple `sys.call()` pass the checks, but the code won't work as it should be. It returns the `display` function always. The whole idea here is to know whether current info box element was called from within `info_panel` or not. If so then the `position` argument must be overwritten to that used in `info_panel` and css `position`needs be removed (so that elements do not overlap).
I've modified it to nicer and safer solution with `tryCatch`

**Comment by mdubel** [comment]
@dokato what is the status of this PR?

**Comment by dokato** [comment]
@mdubel I'm not a big fan of tryCatch solution. I'm trying to figure out if there is a way to parse `sys.call` output in a smarter way.

**Comment by dokato** [comment]
After closer look LGTM
